### ISSUE TITLE
Littlebird Stripe

### ISSUE THREAD

**Issue by SM-BJS** [StowMarines/StowMarines-ReTexture-Mod#10]
Following the feedback from last week's debrief, this is what I have in mind:
![image](https://user-images.githubusercontent.com/68105236/169853503-46fecd0e-ae35-465c-a278-7ab1070fe70c.png)
^ The red stripe being the 2 blue colours of the SM Flag (dark and light)
![Screenshot 2022-05-23 at 16 25 35](https://user-images.githubusercontent.com/68105236/169853725-dc8d7c27-943c-42bd-adb2-a9f2cc7f354d.png)
[![image](https://user-images.githubusercontent.com/68105236/169853809-bcfc8d45-b9b1-443e-ae97-b445960ab1d5.png)
](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.shutterstock.com%2Fimage-illustration%2Fcheerful-cartoon-blue-helicopter-yellow-stripe-1779382973&psig=AOvVaw33AJK0WxffB-oWs7JWioD-&ust=1653405794326000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCNDs-P729fcCFQAAAAAdAAAAABAJ)

**Comment by Halliwedge** [comment]
I'll check how fucked the UV is and let you know

**Comment by Halliwedge** [comment]
UV is pretty EZ. Working on ideas now

**Comment by SM-BJS** [comment]
Am I good to complete this request @Halliwedge ?
