### ISSUE TITLE
Prof Uniform Retexture

### ISSUE THREAD

**Issue by Halliwedge** [StowMarines/StowMarines-ReTexture-Mod#11]
U_C_ArtTShirt_01_v1_F_ca.paa
Requested by prof,
Add name and patched to arm
Recolour shirt and shoes to black.

**Comment by Halliwedge** [comment]
![Prof_uniform_co](https://user-images.githubusercontent.com/68269584/170894585-47166680-0246-4359-99a1-dc2e5ac7f695.png)

**Comment by Jronz23** [comment]
dun
