### ISSUE TITLE
ALJXT - Farmers outfit Re texture

### ISSUE THREAD

**Issue by ALJXT** [StowMarines/StowMarines-ReTexture-Mod#13]
By chance is it possible to get the farmers outfit top to be made black with my logo on one sleeve and a sheep on the other and the jeans be made darker without dirt and the wellies to be made darker without the dirt so it looks new and fresh ty ly halli

**Comment by SM-BJS** [comment]
Carried over to the new Discord forums feature: https://discord.com/channels/424105874710331392/1037825015808282674
