### ISSUE TITLE
Blackhawk doesn't appear in Zeus

### ISSUE THREAD

**Issue by SM-BJS** [StowMarines/StowMarines-ReTexture-Mod#2]
Item/Vehicle in question: UH-60M Blackhawk

When/Where it occurred: In Zeus

Details: The UH-60M Blackhawk does not appear in the Zeus Interface even with all unofficial addons allowed.

Media: 
![20210620130637_1](https://user-images.githubusercontent.com/68105236/122673489-9053af80-d1c8-11eb-83b6-444f535ef9d6.jpg)

**Comment by Jronz23** [comment]
Fixed, also fixed MRZ4 not showing up
