### ISSUE TITLE
Wildcat Retexture

### ISSUE THREAD

**Issue by SM-BJS** [StowMarines/StowMarines-ReTexture-Mod#3]
Item/Vehicle in question: AW159 Wildcat

Details: The current wildcat's texture is quite boring and low quality. Furthermore, there is only 1 or 2 usable vanilla variants. I feel that a grey UK Navy styled variant and a Woodland/Green variation of the UK Navy style would look much better.

Media: 
![20210620131247_1](https://user-images.githubusercontent.com/68105236/122673632-39020f00-d1c9-11eb-85af-861bd346aea1.jpg)
![image](https://user-images.githubusercontent.com/68105236/122673617-1ff95e00-d1c9-11eb-8eb6-a334ba4c6d4b.png)
![image](https://user-images.githubusercontent.com/68105236/122673651-5636dd80-d1c9-11eb-88f0-44668b9d21fe.png)

Type of Request: This could benefit Helios but also the whole unit since it's a common helicopter.

**Comment by Halliwedge** [comment]
Working on it now.

**Comment by Jronz23** [comment]
Implemented
