### ISSUE TITLE
MRZR Render Distance

### ISSUE THREAD

**Issue by SM-BJS** [StowMarines/StowMarines-ReTexture-Mod#4]
Item/Vehicle in question: MRZR4

When/Where it occurred: In the 3DEN Editor, in game in singleplayer and multiplayer and in Zeus

Details: The MRZR4 has a very low render distance. When more than ~100m away from the vehicle it renders with the original desert texture.

Media: 
![20210620142345_1](https://user-images.githubusercontent.com/68105236/122675907-871c1000-d1d3-11eb-99f5-68e43a5e92ab.jpg)
![20210620142437_1](https://user-images.githubusercontent.com/68105236/122675908-897e6a00-d1d3-11eb-8ca8-7461647ca611.jpg)
![20210620142329_1](https://user-images.githubusercontent.com/68105236/122675912-8daa8780-d1d3-11eb-845b-a735592ec300.jpg)
![20210620142334_1](https://user-images.githubusercontent.com/68105236/122675914-90a57800-d1d3-11eb-9242-13eda77e1fe8.jpg)

**Comment by Jronz23** [comment]
Fixed
