### ISSUE TITLE
MRZR 4  "author is not a class" bug

### ISSUE THREAD

**Issue by SM-BJS** [StowMarines/StowMarines-ReTexture-Mod#6]
Item/Vehicle in question: MRZR 4 (Black)

When/Where it occurred: When you open the properties of the asset in the 3DEN Editor

Details: When you double click on the asset in the 3DEN Editor, the below error occurs. Appears to cause no actual issues but still annoying when it appears after each fresh spawn.

Media: 
![20210908220307_1](https://user-images.githubusercontent.com/68105236/132585383-a584d057-8653-4b70-a084-a86446af4b13.jpg)

**Comment by Jronz23** [comment]
Arma has the _**big**_ dumb

Fixed for next version
