### ISSUE TITLE
Backpack retexture

### ISSUE THREAD

**Issue by Baxter0004** [StowMarines/StowMarines-ReTexture-Mod#8]
Item in question:

![20220422163203_1](https://user-images.githubusercontent.com/95487963/164736037-cc82a194-5a38-42c7-91b4-15ea8a24ee1a.jpg)

Details: Tan and Olive Versions of this backpack and Medic Versions with Black Caduceus' 

Media:

This shade of tan would fit the best i believe:
![20220422163214_1](https://user-images.githubusercontent.com/95487963/164736679-0711494f-8d05-41ee-bdc4-e246709e1983.jpg)

Reference: Caduceus 
![image_2022-04-22_164020397](https://user-images.githubusercontent.com/95487963/164737167-f7e1c248-c94c-4282-8e89-a8ed9886012b.png)
![20220422163309_1](https://user-images.githubusercontent.com/95487963/164737064-c4883630-72f0-4d2e-91e5-71e36969576a.jpg)

Type of request: Benefits multiple people as we only have a couple of good looking backpacks

**Comment by Eyeless4g** [comment]
![boonie idea](https://user-images.githubusercontent.com/105134372/167276242-bb756406-0999-4423-b40e-aaad9e7b4f6c.png)
Was thinking of essentially more Boonie variation, for example maybe the same idea with the berets where there is each team colour with the stow marines logo or the individual team logo, also maybe just some additional solid green/brown/yellow coloured boonies for the more militaristic look.

**Comment by SM-BJS** [comment]
Create a new issue and I'll assign it to @Halliwedge

**Comment by Halliwedge** [comment]
unable to edit the 3CB mods as they are locked somehow and cannot be open on any machine.
