### ISSUE TITLE
Boonie Retextures

### ISSUE THREAD

**Issue by Eyeless4g** [StowMarines/StowMarines-ReTexture-Mod#9]
![boonie idea](https://user-images.githubusercontent.com/105134372/168718752-208bfc9a-0718-4f82-bc83-76c221b8d518.png)
Was thinking of essentially more Boonie variation, for example maybe the same idea with the berets where there is each team colour with the stow marines logo or the individual team logo, also maybe just some additional solid green/brown/yellow coloured boonies for the more militaristic look.

**Comment by Halliwedge** [comment]
Getting the colours sorted and doing ingame testing.

**Comment by SM-BJS** [comment]
How's the SITREP on this one looking @Halliwedge ?
